version: '3.8'

services:
  frontend:
    build: ./frontend/
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/
          target: /app
          action: sync
  web:
    build:
      context: .
      target: dev 
    ports:
      - 8000:8000
    environment:
      PORT: ":8000"
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      SECRET: "z&n5Z?T_g7fVtmeP3T8D&=p_}R40U9GW0He,V.&kp"
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart
  db:
    container_name: postgres 
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
